import { AlertRule, PortfolioSnapshot, PreMarketPlan } from "@/lib/types";

export const TARGET_VALUE = 450000;

export const samplePortfolio: PortfolioSnapshot = {
  asOf: "2026-04-25",
  cashAvailable: 14250,
  holdings: [
    {
      ticker: "NVDA",
      name: "NVIDIA",
      quantity: 120,
      avgCost: 625,
      currentPrice: 905,
      marketValue: 108600,
      gainLoss: 33600,
      allocationPct: 24.1,
      assetClass: "Equity",
      sector: "Semiconductors",
      convictionTag: "Semiconductor",
      notes: "AI compute leader; monitor concentration.",
    },
    {
      ticker: "MSFT",
      name: "Microsoft",
      quantity: 90,
      avgCost: 350,
      currentPrice: 430,
      marketValue: 38700,
      gainLoss: 7200,
      allocationPct: 8.6,
      assetClass: "Equity",
      sector: "Software",
      convictionTag: "AI",
      notes: "Core AI/cloud anchor.",
    },
    {
      ticker: "TSLA",
      name: "Tesla",
      quantity: 80,
      avgCost: 260,
      currentPrice: 185,
      marketValue: 14800,
      gainLoss: -6000,
      allocationPct: 3.3,
      assetClass: "Equity",
      sector: "EV",
      convictionTag: "EV",
      fundamentalsWeak: true,
      notes: "Reassess after next delivery print.",
    },
    {
      ticker: "SMH",
      name: "VanEck Semiconductor ETF",
      quantity: 150,
      avgCost: 205,
      currentPrice: 260,
      marketValue: 39000,
      gainLoss: 8250,
      allocationPct: 8.7,
      assetClass: "ETF",
      sector: "Semiconductors",
      convictionTag: "Semiconductor",
      notes: "Diversified semi exposure.",
    },
    {
      ticker: "BTC",
      name: "Bitcoin",
      quantity: 1.8,
      avgCost: 41000,
      currentPrice: 68500,
      marketValue: 123300,
      gainLoss: 49500,
      allocationPct: 27.4,
      assetClass: "Crypto",
      sector: "Crypto",
      convictionTag: "Crypto",
      notes: "Use volatility bands and stop plan.",
    },
    {
      ticker: "ICLN",
      name: "iShares Global Clean Energy ETF",
      quantity: 400,
      avgCost: 17,
      currentPrice: 15,
      marketValue: 6000,
      gainLoss: -800,
      allocationPct: 1.3,
      assetClass: "ETF",
      sector: "Clean Energy",
      convictionTag: "Clean Energy",
      notes: "Small tactical position.",
    },
    {
      ticker: "AMZN",
      name: "Amazon",
      quantity: 75,
      avgCost: 130,
      currentPrice: 180,
      marketValue: 13500,
      gainLoss: 3750,
      allocationPct: 3,
      assetClass: "Equity",
      sector: "Consumer",
      convictionTag: "AI",
      notes: "Cloud margin expansion narrative.",
    },
  ],
};

export const mockPreMarketPlan: PreMarketPlan = {
  marketSentiment: "Neutral",
  fedSummary: "Fed speakers expected to reinforce data-dependent policy stance.",
  macroSummary: "Upcoming jobs and inflation prints likely drive bond yields.",
  sectorSentiment: {
    AI: "Bullish",
    semiconductors: "Bullish",
    EV: "Neutral",
    crypto: "Bullish",
    "clean energy": "Neutral",
  },
  topActions: [
    "Trim oversized winners into strength.",
    "Add high-conviction AI names only on pullbacks.",
    "Maintain disciplined stops for volatile assets.",
  ],
  buyZones: ["NVDA: 3-5% pullback", "SMH: 2-3% pullback", "MSFT: retest of 20DMA"],
  stopLossNotes: [
    "Hard stop: -10% from new entries unless thesis changes.",
    "Trail stops on crypto with volatility-adjusted bands.",
  ],
  alertTriggers: [
    "Semiconductor index breakout with volume.",
    "BTC daily close below 50-day moving average.",
    "Strong buy-side analyst upgrades in AI leaders.",
  ],
};

export const defaultAlertRules: AlertRule[] = [
  { label: "Buy dip alert", description: "Trigger when core holdings drop 3-5% on low-volume pullback.", enabled: true },
  { label: "Breakout alert", description: "Trigger on 20-day high with above-average volume.", enabled: true },
  { label: "Trim alert", description: "Trigger when allocation > 20% and gain > 50%.", enabled: true },
  { label: "Stop-loss alert", description: "Trigger if position falls 10% from entry or thesis breaks.", enabled: true },
  { label: "Strong Buy analyst upgrade alert", description: "Track major upgrade revisions from top sell-side firms.", enabled: false },
  { label: "Earnings risk alert", description: "Trigger 3 trading days before earnings for high-beta names.", enabled: true },
];
